version: '3.3'

services:

  frontend:
    build: ./web/frontend 
    image: rosjana63070145/webfrontend:1.0  
    ports:
      - "8081:8081"
    depends_on:
      - db
  backend:
    build: ./web/backend
    image: rosjana63070145/webbackend:1.0  
    ports:
      - "8088:80"
    depends_on:
      - db

  db:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: myapp
      volumes:
        - ./web/db/my-db.sql:/docker-entrypoint-initdb.d/init.sql